syntasso/kratix-docs

docs/events/2022-kcduk/01-using-multiple-promises.md
docs/events/2022-kcduk/02-writing-a-jenkins-promise.md

Co-authored-by: Colin Humphreys <colin@syntasso.io>

Fix typos and inconsistent filenames

---

docusaurus.config.js

not merging until we want to officially "release" the marketplace

add the marketplace to the navbar

---

docs/_partials/_enhancing-a-promise.md
docs/_partials/_writing-a-promise.md
docs/main/05-reference/05-resources/02-workflows.md
docs/main/05-reference/05-resources/04-status.md
docs/workshop/part-ii/02-service-on-demand.md
docs/workshop/part-ii/03-dependencies.md
docs/workshop/part-ii/04-schedule-promise.md
docs/workshop/part-ii/05-update-status.md

to be merged after https://github.com/syntasso/kratix/pull/20

feat: prepend kratix dirs with `/kratix`

---

docs/main/04-guides/05-compound-promises.mdx
docs/main/05-reference/01-deployment-topology/01-deployment-topology.md
docs/main/05-reference/01-deployment-topology/_category_.json
docs/main/05-reference/02-statestore/_category_.json
docs/main/05-reference/04-promises/02-delete.md
docs/main/05-reference/04-promises/03-updates.md
docs/main/05-reference/04-promises/04-workflows.md
docs/main/05-reference/05-resources/02-workflows.md
docs/main/05-reference/05-resources/03-delete.md
docs/main/05-reference/05-resources/05-updates.md
docs/main/05-reference/06-workflows.md
docs/main/05-reference/07-multidestination-management.md

fixes [#42](https://github.com/syntasso/kratix-docs/issues/42)

Multiple configure pipelines docs (plus tweaks)

---

docs/main/05-reference/07-multidestination-management.md

Remove an inaccurate description on promises scheduling.
cc @richcooper95

Fix: promises scheduled to many dests not just one

---

docs/_partials/_writing-a-promise.md
docs/workshop/part-ii/06-compound-promise.mdx

- instead of kratix-promise-id

fix: use kratix.io/promise-name label

---

docs/main/08-troubleshooting.md

Closes [#67](https://github.com/syntasso/kratix-docs/issues/67)

Add troubleshooting docs

---

docs/ske/02-backstage/03-generator.mdx

Document how to use imagePullSecret for pulling the SKE generator image

SKE backstage generator auth via imagePullSecret

---

docs/main/06-faq.md

The PR details the versioning strategy for Kratix

detail versioning strategy in the FAQ

---

docs/main/05-reference/12-workflows.md

https://github.com/syntasso/kratix/pull/200

document ServiceAccount names

---

docs/main/05-reference/12-workflows.md

Pending merging of https://github.com/syntasso/kratix/issues/197 and https://github.com/syntasso/kratix/issues/198

document new RBAC permissions key

---

docs/main/05-reference/15-resources/04-status.md

feat: document how status works across pipelines

---

docs/ske/01-kratix/00-intro.mdx
docs/ske/01-kratix/01-installation.mdx
docs/ske/01-kratix/01-ske-cli-installation.mdx
docs/ske/01-kratix/02-helm-installation.mdx
docs/ske/50-releases/40-ske-cli.mdx

- https://github.com/syntasso/enterprise-kratix/issues/33
Pending PR because we might need to update with more information.
SKE operator also hasn't been release yet, and we shouldn't get rid of the manifest install flow before we have a release for SKE operator that people can use.

WIP: Document install kratix with SKE operator

---

docs/main/08-troubleshooting.md

This is a feature for OSS kratix, we will merge the docs once we have rolled out this feature
Relates to: https://github.com/syntasso/kratix/issues/226

chore: update Troubleshooting docs to reflect that Works and Workplacements have compressed contents

---

docs/main/05-reference/11-promises/05-releases.md

Docs for https://github.com/syntasso/kratix/pull/244 (which implements https://github.com/syntasso/kratix/issues/242)

feat: auth for promiseRelease http

---

docs/ske/50-releases/10-ske.mdx

Includes OSS feature notes in SKE release notes

Notes v0.6.0

---

docs/_partials/_whats-next.md
docs/main/05-reference/11-promises/04-workflows.md
docs/main/05-reference/12-workflows.md

This relates to issue https://github.com/syntasso/kratix/issues/219

Reconciling promise workflow

---

docs/main/05-reference/12-workflows.md
docs/main/05-reference/16-kratix-config/01-deployment-topology.md
docs/main/05-reference/16-kratix-config/_category_.json

feat: document kratix config

---

docs/ske/50-releases/20-ske-operator.mdx

Ske operator v0.4.1

---

docs/workshop/part-ii/04-status.mdx

People should use OSS kratix for workshop. This does not depend on SKE.

chore: workshop PipelineCompleted -> ConfigureWorkflowCompleted

---

docs/main/05-reference/15-resources/04-status.md
docs/ske/50-releases/10-ske.mdx
docs/workshop/part-ii/04-status.mdx

This relates to https://github.com/syntasso/kratix/pull/259 (updating the `PipelineCompleted` condition to account for multiple Configure Pipelines).

fix: change PipelineCompleted to ConfigureWorkflowCompleted

---

docs/ske/50-releases/10-ske.mdx

feat(ske): update release notes for 0.8.0

---

docs/ske/50-releases/10-ske.mdx

chore: Adding 0.9.0 releaes notes

---

docs/ske/50-releases/30-aspects/10-backstage-generator.mdx

chore: adding release notes for ske-backstage-generate 0.11.0

---

docs/ske/10-integrations/10-backstage/03-generator.mdx

feat: document new BackstageComponent promise usage

---

docs/ske/50-releases/30-backstage.mdx

feat: real v0.12.0 of backstage plugins

---

docs/ske/10-integrations/10-backstage/03-generator.mdx
docs/ske/50-releases/30-aspects/10-backstage-generator.mdx

This relates to issue https://github.com/syntasso/ske-images/issues/70
* document backstagecomponents destinationSelectors
* release ske-backstage-generator `0.12.0`
ske-backstage-generator `0.12.0`
Yes
Yes

docs: document backstagecomponents destinationSelectors

---

docs/workshop/part-i/01-installing-kratix.md
docs/workshop/part-i/02-installing-a-promise.md
docs/workshop/part-i/03-multiple-promise.md
docs/workshop/part-ii/01-writing-your-first-promise.mdx
docs/workshop/part-ii/02-promise-workflows.mdx
docs/workshop/part-ii/03-secrets-and-state.mdx
docs/workshop/part-ii/04-status.mdx
docs/workshop/part-ii/06-compound-promise.mdx

mainly just indentation fixes to make copy/paste easier, plus a new titling layout

Workshop improvements

---

docs/workshop/part-ii/01-writing-your-first-promise.mdx
docs/workshop/part-ii/03-secrets-and-state.mdx
docs/workshop/part-ii/_partials/writing-a-promise/05-resource-workflow.yaml

fix: windows support for workshop and correct some common mistakes

---

docs/ske/10-integrations/02-tfe.mdx
docs/ske/50-releases/30-aspects/20-tfstate-finder.mdx

feat: document tfstatefinder v0.6.0

---

docs/ske/01-kratix/05-ske-operator.mdx
docs/ske/01-kratix/10-configuring-ske/10-via-ske-cli.mdx
docs/ske/01-kratix/10-configuring-ske/11-via-helm.mdx
docs/ske/01-kratix/10-configuring-ske/12-via-manifest.mdx
docs/ske/60-ske-cli/01-reference/04_ske-upgrade.md

*DO NOT MERGE* til next ske operator and ske cli release
This relates to issue https://github.com/syntasso/enterprise-kratix/issues/222
Relates to PR: https://github.com/syntasso/enterprise-kratix/pull/251 
Upcoming version of ske-operator and SKE CLI
No
No

chore: remove post upgrade checks

---

docs/ske/50-releases/30-aspects/20-tfstate-finder.mdx

release tf state finder v0.7.0

---

docs/main/08-troubleshooting.md
docs/ske/50-releases/10-ske.mdx

This PR contains the notes and docs for v0.19.0 of SKE, to be merged when the release is cut

SKE v0.18.0

---

docs/workshop/part-i/01-installing-kratix.md
docs/workshop/part-i/03-multiple-promise.md
docs/workshop/part-ii/03-secrets-and-state.mdx
docs/workshop/part-ii/06-compound-promise.mdx
docs/workshop/part-ii/_partials/writing-a-promise/06-full-promise.yaml

Feedback from recent lavender workshop run.
Pending todo:
No.

workshop: feedback and improvements

---

docs/main/03-reference/17-kratix-config/kratix-config.md

- relates to https://github.com/syntasso/kratix/issues/402

docs: add default imagePullPolicy to example kratix config

---

docs/main/05-kratix-cli/20-reference/00_kratix.md
docs/main/05-kratix-cli/20-reference/07_kratix-init-helm-promise.md
docs/main/05-kratix-cli/20-reference/08_kratix-init-crossplane-promise.md
docs/main/05-kratix-cli/20-reference/08_kratix-init-tf-module-promise.md
docs/main/05-kratix-cli/20-reference/11_kratix-update-api.md
scripts/generate-cli-docs

* [no] Is this PR about a feature in an upcoming SKE release?
* [no] Have you cut that new SKE release?
* [no] Have you updated the release notes?

feat: update docs for CLI release 0.5.0

---

docs/_partials/installation/_install-setup-destination.md
docs/main/04-guides/04-new-destination.mdx
docs/main/04-guides/05-compound-promises.mdx
docs/main/06-how-kratix-complements/04-kratix-and-backstage.md
docs/ske/10-integrations/02-tfe.mdx
docs/workshop/part-i/01-installing-kratix.md

https://github.com/syntasso/kratix/pull/433

docs: set destination path in all places in docs

---

docs/main/03-reference/13-destinations/01-destinations.md
docs/main/03-reference/17-kratix-config/kratix-config.md
docs/ske/50-releases/10-ske.mdx

docs: document feature for ske 0.21

---

docs/main/03-reference/13-destinations/01-destinations.md
docs/ske/50-releases/10-ske.mdx

Ske 0.22.0

---

docs/main/03-reference/17-kratix-config/kratix-config.md
docs/ske/50-releases/10-ske.mdx

- Also add new configuration settings to the reference doc

feat: release ske v0.23.0

---

docs/main/06-how-kratix-complements/02-kratix-and-terraform.md
docs/workshop/00-intro.md

Documentation small spelling mistake fix, or references

Basic documentation fixes

---

docs/main/03-reference/11-promises/06-workflows.md
docs/main/03-reference/15-resources/02-workflows.md
docs/main/03-reference/17-kratix-config/kratix-config.md

- Related to https://github.com/syntasso/kratix/issues/228

[release notes for ske 0.25.0] feat: add configurable reconciliation interval docs 

---

docs/_partials/installation/_configure-metrics-collection.md
docs/_partials/installation/_install-cert-manager.md
docs/main/04-guides/01-installing-kratix/01-azure.mdx
docs/main/04-guides/01-installing-kratix/02-aws.mdx
docs/main/04-guides/01-installing-kratix/03-gcp.mdx
docs/main/04-guides/01-installing-kratix/04-openshift.mdx
docs/main/04-guides/01-installing-kratix/05-others.mdx

chore: [release notes for 0.26.0] document how to configure metrics collection 

---

docs/ske/50-releases/10-ske.mdx

chore: add v0.26.0 release notes

---

docs/workshop/part-ii/03-secrets-and-state.mdx

Couple people have copied the dockerfile snippet and replaced the whole dockerfile. This commit make the required change more obvious and people can do a whole copy and replace if they'd like to.
Not related to any SKE version or releases.

chore: install full dockerfile definition in workshop step

---

yarn.lock

Reverts syntasso/kratix-docs#245

Revert "chore(deps): bump @babel/runtime from 7.23.6 to 7.27.1"

---

docs/ske/10-integrations/10-backstage/03-generator.mdx

Waiting for the release to go live before merging.

feat: Document TEMPLATE_SINGLE_SPEC_PAGE field released in ske-backstage gen 0.14.0

---

docs/main/03-reference/12-workflows.md
docs/main/03-reference/15-resources/02-workflows.md
docs/main/03-reference/15-resources/04-status.md
docs/ske/10-integrations/02-tfe.mdx
docs/ske/10-integrations/10-backstage/03-generator.mdx
docs/ske/10-integrations/10-backstage/04-generator-promise.mdx

Related to https://github.com/syntasso/kratix-marketplace/pull/32

chore: remove redundant default namespaces in pipelines

---

docs/ske/50-releases/30-aspects/10-backstage-generator.mdx

docs: add release notes for generator 0.15.0

---

docs/ske/10-integrations/10-backstage/02-plugins.mdx
docs/ske/50-releases/30-backstage.mdx

only merge when the next backstage plugins are released please

[next backstage plugins] feat: release notes and docs for next backstage plugins

---

src/pages/marketplace/index.tsx

update marketplace page to have more info on kratix

---

docs/ske/50-releases/30-aspects/10-backstage-generator.mdx

feat: release v0.16.0

---

docs/main/01-quick-start.md

wip: Update quick start to focus on 3 pillars

---

docs/ske/10-integrations/10-backstage/04-generating-backstage-components.mdx
docs/ske/50-releases/31-backstage-controller.mdx

This relates to issue https://github.com/syntasso/enterprise-kratix/issues/362
Should be merged when next version of backstage-controller is cut.
Not related to SKE

chore: document registry secret requirements for backstage-controller

---

docs/ske/50-releases/30-backstage.mdx

to be merged whenever we release the plugins

feat: next backstage plugin release

---

docs/ske/50-releases/10-ske.mdx
docs/ske/50-releases/30-backstage.mdx

chore: add release notes for SKE v0.28.0

---

docs/main/03-reference/15-resources/04-status.md
docs/main/05-learn-more/03-status-conditions-events/01-promise-status-events.mdx
docs/main/05-learn-more/03-status-conditions-events/02-resource-status-events.mdx
docs/main/05-learn-more/03-status-conditions-events/03-work-status-events.mdx
docs/main/05-learn-more/03-status-conditions-events/_category_.json
docs/ske/50-releases/10-ske.mdx

release notes and docs for SKE 0.29.0

---

docs/ske/01-kratix/10-configuring-ske/10-via-ske-cli.mdx
docs/ske/50-releases/40-ske-cli.mdx
docs/ske/60-ske-cli/01-reference/04_ske-upgrade.md

Co-authored-by: Aslan Avci <alparslan@syntasso.io>

feat(#142): ske-cli upgrade --version docs

---

docs/main/04-guides/06-health-checks.mdx
docs/ske/05-guides/10-healthchecks.mdx

[ske  0.32.0] Feat/documenting multiple healthrecords

---

docs/ske/50-releases/10-ske.mdx

chore: creating ske 0.32.0 release notes

---

docs/ske/01-installing-ske/21-backup-and-restore.mdx

docs: add page for ske backup and restore

---

docs/ske/50-releases/30-backstage.mdx

Add release notes for latest backstage plugins.

chore: add latest backstage plugin releases

---

docs/ske/50-releases/10-ske.mdx

chore: add ske v0.34.0 release notes

---

docs/ske/01-installing-ske/02-advanced-install.mdx
docs/ske/01-installing-ske/03-air-gapped.mdx
docs/ske/50-releases/10-ske.mdx
docs/ske/50-releases/20-ske-operator.mdx

Co-authored-by: Chunyi Lyu <chunyi@syntasso.io>

feat: release ske 0.37.0 and operator v0.17.0
