docs/_partials/_enhancing-a-promise.md, docs/_partials/_install-promise.md, docs/_partials/_using-multiple-promises.md, docs/_partials/_writing-a-promise.md
- to avoid any resources being left behind in race conditions between deleting RR resources and worker cluster resources
[#183839313]
=> fix: Delete RR's first in cleanup steps for workshop

.github/workflows/deploy-to-ghpages.yml, .github/workflows/update-algolia.yml, algolia-config.json, docs/main/01-intro.md, docusaurus.config.js
1. Move the ‘How Kratix Complements’ to the main level. It’s a frequent enough topic that Abby and I were thinking it should stand on its own.
1. Stop auto-expanding to docs menu. There are enough top level things that I feel like now it’s hard to scan and know where to go. Making this change will mean we have the default behaviour for docs for docusaurus. I would want to do this no matter what we decided to do for (1).
=> Move "Kratix complements" nav and collapse nav bar

docs/ske/01-backstage.mdx
Updates the SKE docs to include instructions for writing Promise and Resource Components with all of the new annotations and metadata.
fixes syntasso/backstage#10
=> chore: update SKE docs to reflect Promise and Resource entities

docs/ske/01-backstage.mdx
Adds documentation for all fields that we support for Git config.
This brings the docs in-line with what the code _currently_ looks like (in the latest release); there are no corresponding functionality changes.
=> fix: update docs to include all Git config fields

docs/main/05-reference/11-promises/01-intro.md
This is not extensive, but will help clarify _why_ people may want to use this field.
I suspect we will want to have a 'coming soon' aspect to these docs which highlights the idea of installing and managing these dependencies, but that would require a new page so I am keeping this update light weight for now
=> chore: short extension of requiredPromise behaviour

docs/_partials/installation/_install-cert-manager.md
closes #93 , related to https://github.com/syntasso/kratix/issues/202
=> Document how to use custom certifcates instead of cert-manager

docs/main/05-reference/13-destinations/02-multidestination-management.md, docs/main/08-troubleshooting.md, docs/ske/10-integrations/10-backstage/03-generator.mdx, docs/workshop/part-ii/04-status.mdx
Document the `ske-backstage-component` Promise for writing multiple status updates to the same Backstage Component in a Resource Configure workflow.
=> feat: document the ske-backstage-component promise

src/data/promise-data.json
This promise confuses people as it is based on an older format of Kratix before we had PromiseReleases.
Not deleting the Promise yet as it is referenced in a few other places, but want to get it our of the front page.
=> Remove paved path as marketplace example as out of date

docs/main/06-kratix-cli/20-reference/07_kratix-init-helm-promise.md, docs/ske/50-releases/40-ske-cli.mdx
This has come up in the community slack and may be nice to have the information more readily accessible for people.
Implemented as a new "info" box and looks like this:
=> chore: add explanation marking CLI as safe on mac

docs/ske/01-kratix/11-helm-installation.mdx, docs/ske/50-releases/20-ske-operator.mdx
This relates to issue https://github.com/syntasso/enterprise-kratix/issues/150
=> fix: remove references to imageRegistry.tag as this has been deprecated

docs/ske/01-kratix/01-air-gapped.mdx, docs/ske/01-kratix/10-ske-cli-installation.mdx
This was based on our discussion earlier today in huddle.
The changes are depicted here:
=> chore: make it clearer that air-gapped has to be helm install for now

docs/workshop/part-0/02-create-clusters.mdx
this is a cross repo change and depends on the change in kratix to the quickstart
=> chore: rename all references to kratix-bucket to kratix

docs/main/03-reference/12-workflows.md
Found out the typo as part of https://github.com/syntasso/kratix/pull/363
Should be resouceNames, see k8s api reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#policyrule-v1-rbac-authorization-k8s-io
=> fix: should be resourceNames

docs/main/03-reference/11-promises/06-workflows.md, docs/main/03-reference/15-resources/02-workflows.md, docs/main/08-troubleshooting.md, docs/ske/50-releases/10-ske.mdx
This relates to issue [#383](https://github.com/syntasso/kratix/issues/383).
Added sections for both Promise and Resource Delete workflows.
=> docs: add manual reconciliation for delete workflow sections

docs/workshop/part-ii/03-secrets-and-state.mdx, src/css/custom.scss
closes #221 
Highlight in light:
Highlight in dark:
not related to any feature or release
=> chore: make block highlight more obvious

docs/workshop/part-ii/03-secrets-and-state.mdx, docs/workshop/part-ii/06-compound-promise.mdx, docs/workshop/part-ii/_partials/compound-promise/01-full-promise.yaml, docs/workshop/part-ii/_partials/secrets-and-state/04-full-promise.yaml
closes #205 
- so people can have a reference point if they would like to double check the promise.yaml; added to section c and e because they actively edit the promise.yaml
-
=> chore: include full promise definition in workshop

package.json, src/components/GiscusComponent/index.tsx, src/theme/BlogPostItem/index.tsx, yarn.lock
Giscus is a simple toolkit that uses Github discussions to add a comment section to pages. This PR enables it for Blog posts.
The comment box can be disabled with frontMatter "disableComments: true"
Screeshoots:
[light mode]
[dark mode]
=> feat: introduce giscus comments to the blogs

src/data/promise-data.json
Point marketplace to the better support app-as-a-service example in the correct repo.
=> chore: update app-as-a-service to marketplace URL

docs/main/03-reference/12-workflows.md
Standardise KRATIX_ prefix for envvars and expose the object name in the pipeline images by default. This allows people to do more useful inline containers as they can use vars that are unique.
Docs for https://github.com/syntasso/kratix/pull/456
=> feat: expose more envvars for pipeline containers

yarn.lock
Reverts syntasso/kratix-docs#244
=> Revert "chore(deps): bump estree-util-value-to-estree from 3.0.1 to 3.3.3"

blog/2025-05-27-healthchecks-progressive-rollout/index.mdx
This relates to issue # https://github.com/syntasso/kratix-docs/issues/263
=> docs: progressive rollout blog

docs/main/04-guides/02-installing-gitops-agent/01-flux.mdx, docs/ske/10-integrations/20-port.mdx
=> chore: fix up reference to fluxcd docs for secret

docs/main/03-reference/11-promises/03-updates.md
- will be released in the next SKE
Related to PR of kratix https://github.com/syntasso/kratix/pull/484
Will be released in the next SKE
=> docs: misscheduled -> misplaced

docs/workshop/part-ii/06-compound-promise.mdx
Postgres versions have bumped which means v1alpha1 is now v1alpha2.
Tested against full workshop.
=> fix: bump version of postgres promise in pipeline script
